export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";

/* AUTH */

export const CHECK_SESSION = "CHECK_SESSION";
export const CHECK_SESSION_SUCCESS = "CHECK_SESSION_SUCCESS";
export const CHECK_SESSION_FAILED = "CHECK_SESSION_FAILED";
export const VERIFY = "VERIFY";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILED = "VERIFY_FAILED";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
